serverAddr = "127.0.0.1"
serverPort = 7000

[[proxies]]
name = "secret_tcp"
type = "stcp"
secretKey = "abcdefg"
localIP = "192.168.0.172"
localPort = 22714
allowUsers = ["*"]

[[proxies]]
name = "p2p_tcp"
type = "xtcp"
secretKey = "abcdefg"
localIP = "192.168.0.172"
localPort = 22714
allowUsers = ["*"]
