serverAddr = "127.0.0.1"
serverPort = 7000

[[visitors]]
name = "secret_tcp_visitor"
type = "stcp"
serverName = "secret_tcp"
secretKey = "abcdefg"
bindAddr = "127.0.0.1"
bindPort = 16000

[[visitors]]
name = "p2p_tcp_visitor"
type = "xtcp"
serverName = "p2p_tcp"
secretKey = "abcdefg"
bindAddr = "127.0.0.1"
bindPort = 16001
keepTunnelOpen = false
maxRetriesAnHour = 8
minRetryInterval = 90
# fallbackTo = "stcp_visitor"
# fallbackTimeoutMs = 500