kind: pipeline
type: docker
name: gostc-admin

platform:
  os: linux
  arch: amd64

steps:
  - name: build-web
    image: node:18
    volumes:
      - name: npm-cache
        path: /drone/src/web/node_modules
    commands:
      - mkdir output
      - cd web
      - npm install
      - npm run build
      - mv dist ../output/
  - name: build-web-zip
    image: alpine:latest
    commands:
      - cd output
      - apk add zip
      - zip -r dist.zip dist

  - name: build-server
    image: golang:1.23-alpine
    volumes:
      - name: go-cache
        path: /go/pkg/mod/
    commands:
      - cd server
      - mv ../output/dist.zip ./web/
      - go env -w GO111MODULE=on
      - go env -w GOPROXY=https://goproxy.cn,direct
      - go mod tidy
      - go build -ldflags "-s -w" -o ../output/server main.go

  - name: docker-build-push
    image: plugins/docker
    settings:
      registry: harbor.sian.one
      repo: harbor.sian.one/gostc/gostc-admin
      username:
        from_secret: HARBOR_USERNAME
      password:
        from_secret: HARBOR_PASSWORD
      tags:
        - latest
      dockerfile: Dockerfile


volumes:
  - name: go-cache
    host:
      path: /home/drone/build/go-cache/
  - name: npm-cache
    host:
      path: /home/drone/build/npm-cache/


trigger:
  branch:
    - master