version: 2

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    targets:
#      - darwin_amd64
#      - darwin_arm64
#      - linux_amd64
#      - linux_arm64
      - windows_amd64
      - windows_arm64
    ldflags:
      - -s
      - -w
    binary: >-
      server
    main: main.go
archives:
  - format: tar.gz
    name_template: "server_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip
