version: 2

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    targets:
      - freebsd_386
      - freebsd_amd64
      - darwin_amd64
      - darwin_arm64
      - linux_arm64
      - linux_amd64
      - linux_amd64_v3
      - windows_arm64
      - windows_amd64
      - windows_amd64_v3
    ldflags:
      - -s
      - -w
    binary: >-
      server
    main: ./main.go
archives:
  - format: tar.gz
    name_template: "server_{{ .Target }}"
    format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE
