name: Build

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Extract Tag
        id: extract_tag
        run: |
          # 提取标签名（去掉前面的v）
          TAG_NAME=$(echo ${{ github.ref }} | sed 's/refs\/tags\/v//')
          echo "DOCKER_TAG=$TAG_NAME" >> $GITHUB_ENV

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        working-directory: ./web
        run: npm install

      - name: Build frontend
        working-directory: ./web
        run: npm run build

      - name: Compress dist directory
        working-directory: ./web
        run: zip -r dist.zip dist

      - name: Move dist.zip to backend directory
        run: mv web/dist.zip server/web/

      - name: Build backend
        uses: goreleaser/goreleaser-action@v4
        with:
          distribution: goreleaser
          version: latest
          args: release --snapshot --clean --timeout 300m
          workdir: ./server

      - name: Build client
        uses: goreleaser/goreleaser-action@v4
        with:
          distribution: goreleaser
          version: latest
          args: release --snapshot --clean
          workdir: ./client


      - name: Build proxy
        uses: goreleaser/goreleaser-action@v4
        with:
          distribution: goreleaser
          version: latest
          args: release --snapshot --clean
          workdir: ./proxy

      - name: Upload release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            ./server/dist/*.tar.gz
            ./server/dist/*.zip
            ./client/dist/*.tar.gz
            ./client/dist/*.zip
            ./proxy/dist/*.tar.gz
            ./proxy/dist/*.zip

      - name: Login Docker
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Docker buildx client
        run: |
          cd client
          docker buildx create --name gostc-builder --use
          docker buildx build --platform linux/386,linux/amd64,linux/arm/v7,linux/arm64,linux/s390x -t sianhh/gostc:latest -t sianhh/gostc:${{ env.DOCKER_TAG }} --push .
          docker buildx rm gostc-builder

      - name: Docker buildx server
        run: |
          cd server
          docker buildx create --name gostc-admin-builder --use
          docker buildx build --platform linux/amd64,linux/arm64 -t sianhh/gostc-admin:latest -t sianhh/gostc-admin:${{ env.DOCKER_TAG }} --push .
          docker buildx rm gostc-admin-builder

      - name: Docker buildx proxy
        run: |
          cd proxy
          docker buildx create --name gostc-proxy-builder --use
          docker buildx build --platform linux/386,linux/amd64,linux/arm/v7,linux/arm64,linux/s390x -t sianhh/gostc-proxy:latest -t sianhh/gostc-proxy:${{ env.DOCKER_TAG }} --push .
          docker buildx rm gostc-proxy-builder